(package "grip-mode" "1.0.0" "Instant GitHub-flavored Markdown/Org preview using grip")

(website-url "https://github.com/seagle0128/grip-mode")
(keywords "convenience" "markdown" "preview")

(package-file "grip-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(files "*.el")

(source "melpa")

(depends-on "emacs" "24.4")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
